layout: {zmk_keyboard: corneish_zen, layout_name: foostan_corne_6col_layout}
layers:
  QWERTY:
  - [ESC, Q, W, E, R, T, Y, U, I, O, P, Å]
  - [LCTRL, A, S, D, F, G, H, J, K, L, Ö, Ä]
  - ['⇧', Z, X, C, V, B, N, M, ',', '.', '-', '↵']
  - - $$mdi:apple$$
    - NUM CON
    - {t: '⌫', s: '⌦'}
    - '␣'
    - SYM NAV
    - '⌥'
  NUMBER:
  - - ESC
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - '⇥'
    - 7
    - 8
    - 9
    - '/'
    - '*'
  - - LCTRL
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - ','
    - 4
    - 5
    - 6
    - '-'
    - '+'
  - - {t: '⇧', s: CAPSWORD}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - 0
    - 1
    - 2
    - 3
    - "."
    - '='
  - - $$mdi:apple$$
    - QWERTY
    - {t: '⌫', s: '⌦'}
    - '␣'
    - QWERTY
    - '⌥'
  SYMBOL:
  - [ESC, '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '`']
  - [LCTRL, '¨', '´', '', '€', '', '"', '=', '[', ']', '|', '~']
  - [{t: '⇧', s: CAPSWORD}, '§', "'", '?', '<', '>', '/', '+', '{',
'}', '\', '↵']
  - - $$mdi:apple$$
    - QWERTY
    - {t: '⌫', s: '⌦'}
    - '␣'
    - QWERTY
    - '⌥'
  CONTROL:
  - [ESC, 'boot loader', 'sys reset', 'studio unlock', 'soft off',
  $$mdi:usb$$, $$mdi:volume-plus$$, F1, F2, F3, F4, $$mdi:brightness-5$$]
  - - {t: CLEAR, s: $$mdi:bluetooth$$}
    - {t: 0, s: $$mdi:bluetooth$$}
    - {t: 1, s: $$mdi:bluetooth$$}
    - {t: 2, s: $$mdi:bluetooth$$}
    - {t: 3, s: $$mdi:bluetooth$$}
    - {t: 4, s: $$mdi:bluetooth$$}
    - $$mdi:volume-minus$$
    - F5
    - F6
    - F7
    - F8
    - $$mdi:brightness-4$$
  - [{t: '⇧', s: CAPSWORD}, '⏮', '⏯', '◼', '⏭', '⎙',
$$mdi:volume-mute$$, F9, F10, F11, F12, '↵']
  - - $$mdi:apple$$
    - QWERTY
    - {t: '⌫', s: '⌦'}
    - '␣'
    - QWERTY
    - '⌥'
  NAVIGATION:
  - [ESC, {t: 'MB 1', s: $$mdi:mouse$$}, {t: 'MB 2', s: $$mdi:mouse$$}, {t: 'MB 3', s: $$mdi:mouse$$}, {t: 'MB 4', s: $$mdi:mouse$$}, {t: 'MB 5', s: $$mdi:mouse$$},
HOME, PG DN, PG UP, END, '', '⇥']
  - [LCTRL, {t: '←', s: $$mdi:mouse$$}, {t: '↓', s: $$mdi:mouse$$}, {t: '↑', s: $$mdi:mouse$$}, {t: '→', s: $$mdi:mouse$$}, '',
'←', '↓', '↑', '→', '', INS]
  - [{t: '⇧', s: CAPSWORD}, 'scroll ←', 'scroll ↓', 'scroll
↑', 'scroll →', '', '', '', '', '', '', '↵']
  - - $$mdi:apple$$
    - QWERTY
    - {t: '⌫', s: '⌦'}
    - '␣'
    - QWERTY
    - '⌥'
